import React from 'react'
import ReactDOM from 'react-dom/client'
import { registerSW } from 'virtual:pwa-register'
import '@fontsource-variable/archivo'
import App from './App.jsx'
import ErrorBoundary from './components/ErrorBoundary.jsx'
import './index.css'

// Register the auto-updating service worker (generated by vite-plugin-pwa)
registerSW({ immediate: true })

const root = ReactDOM.createRoot(document.getElementById('root'))
const params = new URLSearchParams(window.location.search)

// Alternative Einstiege abseits der App: die Screen-Previews existieren nur im
// Dev-Build (sie rendern echte Screens und würden sonst echten Spielstand
// schreiben); die read-only ZUT-Galerie bleibt auch im Deploy-Preview erreichbar.
async function pickAltRoot() {
  if (import.meta.env.DEV && params.get('zut-preview')) {
    const loaders = {
      pack: () => import('./components/dev/PreviewPack.jsx'),
      album: () => import('./components/dev/PreviewAlbum.jsx'),
      match: () => import('./components/dev/PreviewMatch.jsx'),
      loop: () => import('./components/dev/PreviewLoop.jsx'),
    }
    const load = loaders[params.get('zut-preview')]
    if (load) return (await load()).default
  }
  if (params.has('zut-gallery')) {
    return (await import('./components/ZutGallery.jsx')).default
  }
  return null
}

pickAltRoot().then((AltRoot) => {
  root.render(
    <React.StrictMode>
      <ErrorBoundary>
        {AltRoot ? <AltRoot /> : <App />}
      </ErrorBoundary>
    </React.StrictMode>,
  )
})
